### ISSUE TITLE
import tinyMCEReSourcePath from "/tinyMCE?url";  找不到咋整

### ISSUE THREAD

**Issue by qzzhujixue** [l123wx/tinyMCE-docx-preview-demo#1]
16:28:46 [vite] Pre-transform error: Failed to resolve import "/tinyMCE?url" from "src/components/TinyMCE.vue". Does the file exist?
16:28:47 [vite] Internal server error: Failed to resolve import "/tinyMCE?url" from "src/components/TinyMCE.vue". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/test/tinyMCE-docx-preview-demo-master/src/components/TinyMCE.vue:28:36
  4  |  import { fromBuffer } from "file-type/core";
  5  |  import useTinyMCE from "../hooks/useTinyMCE";
  6  |  import tinyMCEReSourcePath from "/tinyMCE?url";
     |                                   ^
  7  |  import { Buffer } from "buffer";
  8  |  window.Buffer = window.Buffer || Buffer;

**Comment by qzzhujixue** [comment]
大佬

**Comment by l123wx** [comment]
修复了，你再试试 [8d70af7](https://github.com/l123wx/tinyMCE-docx-preview-demo/commit/8d70af77e1dcc9f22e79bbc50c9ee629c353efde)

**Comment by qzzhujixue** [comment]
谢谢
