### ISSUE TITLE
大佬，为啥我新建的docx文件可以，我之前的大部分docx为啥不行报错；但是我只要修改一下也可以了，是wps版本问题吗？

### ISSUE THREAD

**Issue by qzzhujixue** [l123wx/tinyMCE-docx-preview-demo#2]
大佬，为啥我新建的docx文件可以，我之前的docx为啥不行报错；但是我只要修改一下也可以了，例如我增加几个字保存下
[Linux根分区扩容.docx](https://github.com/l123wx/tinyMCE-docx-preview-demo/files/14597410/Linux.docx)

**Comment by qzzhujixue** [comment]
<img width="561" alt="截取图片_20240314135835" src="https://github.com/l123wx/tinyMCE-docx-preview-demo/assets/16644444/f0795186-5021-45c8-9370-87dcb370aca6">

**Comment by l123wx** [comment]
我看了一下这个报错是 docx-preview.js，这个库报的，你可以去他的 [仓库](https://github.com/VolodymyrBaydalka/docxjs) 看看，后面还有这种问题的话可以先在他提供的demo试一下：[DEMO](https://volodymyrbaydalka.github.io/docxjs/)

**Comment by l123wx** [comment]
我已经修复了这个问题，并且给他提了 PR：[Click Here](https://github.com/VolodymyrBaydalka/docxjs/pull/101)，你可以等他合并，或者手动修改一下源代码 @qzzhujixue

**Comment by millet0328** [comment]
wps版本问题，wps最新版另存为你的linux.docx一份文件，实测没有问题，你应该升级一下wps，我的版本是wps365。
另外，经过我实测，wps生成的docx文件，在分页的时候跟office差异较大。
wps生成的docx中一大段文字会溢出一个页面，
office生成的docx中大段文字有可能正常显示。

**Comment by qzzhujixue** [comment]
> wps版本问题，wps最新版另存为你的linux.docx一份文件，实测没有问题，你应该升级一下wps，我的版本是wps365。 另外，经过我实测，wps生成的docx文件，在分页的时候跟office差异较大。 wps生成的docx中一大段文字会溢出一个页面， office生成的docx中大段文字有可能正常显示。

大佬，可是很多资料都是老版本的啊。。。不能不管了呀；我重新编辑下倒是不报错了，但是用户历史资料相当多o(╥﹏╥)o

**Comment by qzzhujixue** [comment]
> 我已经修复了这个问题，并且给他提了 PR：[Click Here](https://github.com/VolodymyrBaydalka/docxjs/pull/101)，你可以等他合并，或者手动修改一下源代码 @qzzhujixue

大佬，nb
